# Static exposes metric samples with static labels and values.
static:
  # Gauges exports gauges with static labels and values via samples.
  gauges:
    - name: "cosmos_asset_exponent" # Required
      description: "Exponent value for a Cosmos asset" # Optional but recommended
      labels: [ "chain", "denom" ]
      samples:
        # In the below, the labels are the label values.
        - { labels: [ "agoric-emerynet-5", "ubld" ], value: 6 }
        - { labels: [ "axelar-dojo-1", "uaxl" ], value: 6 }
        - { labels: [ "cosmoshub-4", "uatom" ], value: 6 }
        - { labels: [ "crescent-1", "ucre" ], value: 6 }
        - { labels: [ "injective-1", "inj" ], value: 18 }
        - { labels: [ "juno-1", "ujuno" ], value: 6 }
        - { labels: [ "osmosis-1", "uosmo" ], value: 6 }
        - { labels: [ "sommelier-3", "usomm" ], value: 6 }
        - { labels: [ "theta-testnet-001", "uatom" ], value: 6 }

# Cosmos metrics gather and export metrics for Cosmos chains.
cosmos:
  # The canonical chain id.
  - chainID: cosmoshub-4
    # Periodically polls REST API (aka LCD) for data such as block height. At least one REST url is required.
    interval: 15s # Optional. How often to poll the REST API. Default is 15s.
    rest:
      - url: https://api.cosmoshub.strange.love
      - url: https://api-cosmoshub-ia.cosmosia.notional.ventures
    validators:
      # The consensus address of a validator.
      - consaddress: cosmosvalcons164q2kq3q3psj436t9p7swmdlh39rw73wpy6qx6
