# Static exposes metric samples with static labels and values.
static:
  gauges:
    - name: "cosmos_asset_exponent" # Required
      description: "Exponent value for a Cosmos asset" # Optional but recommended
      labels: [ "chain", "denom" ]
      samples:
      - { labels: [ "agoric-emerynet-5", "ubld" ], value: 6 }
      - { labels: [ "axelar-dojo-1", "uaxl" ], value: 6}
      - { labels: [ "cosmoshub-4", "uatom" ], value: 6 }
      - { labels: [ "crescent-1", "ucre" ], value: 6 }
      - { labels: [ "injective-1", "inj" ], value: 18 }
      - { labels: [ "juno-1", "ujuno" ], value: 6 }
      - { labels: [ "osmosis-1", "uosmo" ], value: 6 }
      - { labels: [ "sommelier-3", "usomm" ], value: 6 }
      - { labels: [ "theta-testnet-001", "uatom" ], value: 6 }

metrics:
  public_rpc_node_height:
    description: "Node height of a public RPC node"
    labels: [ "chain_id", "source" ]
    chains:
      - name: agoric-emerynet-5
        rpcs:
          - https://agoric-rpc.easy2stake.com
          - https://agoric-rpc.polkachu.com
      - name: axelar-dojo-1
        rpcs:
          - https://axelar-rpc.quantnode.tech
          - https://rpc.axelar.bh.rocks
