# Static exposes metric samples with static labels and values.
static:
  # Gauges exports gauges with static labels and values via samples.
  gauges:
    - name: "cosmos_asset_exponent" # Required
      description: "Exponent value for a Cosmos asset" # Optional but recommended
      labels: [ "chain", "denom" ]
      samples:
        # In the below, the labels are the label values.
        - { labels: [ "agoric-emerynet-5", "ubld" ], value: 6 }
        - { labels: [ "axelar-dojo-1", "uaxl" ], value: 6 }
        - { labels: [ "cosmoshub-4", "uatom" ], value: 6 }
        - { labels: [ "crescent-1", "ucre" ], value: 6 }
        - { labels: [ "injective-1", "inj" ], value: 18 }
        - { labels: [ "juno-1", "ujuno" ], value: 6 }
        - { labels: [ "osmosis-1", "uosmo" ], value: 6 }
        - { labels: [ "sommelier-3", "usomm" ], value: 6 }
        - { labels: [ "theta-testnet-001", "uatom" ], value: 6 }

# Gather and export metrics for Cosmos chains.
cosmos:
  # Required. Recommended value is the canonical chain id, but can be any arbitrary string to identify the cosmos chain.
  - chain: cosmoshub-4
    # If present, periodically polls for CometBFT (formerly Tendermint) data such as block height.
    rpc:
      - url: https://cosmos-rpc.polkachu.com
        interval: 5s # Optional. Polling interval. Defaults to 5s.
      - url: https://rpc.cosmoshub.strange.love
        # Not supported yet, but data structure allows extensions to support authenticating with RPC providers.
        # headers:
        #  X-API-KEY: my-api-key
